<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Portfolio;
use Illuminate\Support\Facades\DB;

class PortfoliosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('portfolios')->delete();
        
        Portfolio::insert([
            [
                'title' => 'CLASSIC HOTEL PROJECT',
                'slug' => 'classic-hotel-project',
                'description' => 'Projeto de hotel clássico com arquitetura sofisticada.',
                'status' => 1,
                'location' => 'Melbourne VIC, Austrália',
                'type' => 'Hotel',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'RESORT BEACH',
                'slug' => 'resort-beach',
                'description' => 'Resort à beira-mar com design contemporâneo.',
                'status' => 1,
                'location' => 'Gold Coast, Austrália',
                'type' => 'Resort',
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'URBAN LOFT',
                'slug' => 'urban-loft',
                'description' => 'Loft urbano com conceito aberto e industrial.',
                'status' => 1,
                'location' => 'São Paulo, Brasil',
                'type' => 'Residencial',
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CORPORATE TOWER',
                'slug' => 'corporate-tower',
                'description' => 'Torre corporativa de alto padrão.',
                'status' => 1,
                'location' => 'Dubai, Emirados Árabes Unidos',
                'type' => 'Corporativo',
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'MODERN VILLA',
                'slug' => 'modern-villa',
                'description' => 'Vila moderna com integração à natureza.',
                'status' => 1,
                'location' => 'Ibiza, Espanha',
                'type' => 'Residencial',
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'INDUSTRIAL COMPLEX',
                'slug' => 'industrial-complex',
                'description' => 'Complexo industrial sustentável.',
                'status' => 1,
                'location' => 'Hamburgo, Alemanha',
                'type' => 'Industrial',
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'MOUNTAIN CHALET',
                'slug' => 'mountain-chalet',
                'description' => 'Chalé de montanha com vista panorâmica.',
                'status' => 1,
                'location' => 'Aspen, EUA',
                'type' => 'Residencial',
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'LUXURY APARTMENTS',
                'slug' => 'luxury-apartments',
                'description' => 'Apartamentos de luxo no centro urbano.',
                'status' => 1,
                'location' => 'Paris, França',
                'type' => 'Residencial',
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'COASTAL HOUSE',
                'slug' => 'coastal-house',
                'description' => 'Casa costeira com arquitetura sustentável.',
                'status' => 1,
                'location' => 'Florianópolis, Brasil',
                'type' => 'Residencial',
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ART GALLERY SPACE',
                'slug' => 'art-gallery-space',
                'description' => 'Espaço de galeria de arte contemporânea.',
                'status' => 1,
                'location' => 'Nova York, EUA',
                'type' => 'Comercial',
                'sort_order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'COUNTRY HOUSE',
                'slug' => 'country-house',
                'description' => 'Casa de campo com design rústico.',
                'status' => 1,
                'location' => 'Toscana, Itália',
                'type' => 'Residencial',
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'URBAN MALL',
                'slug' => 'urban-mall',
                'description' => 'Shopping center moderno e funcional.',
                'status' => 1,
                'location' => 'Lisboa, Portugal',
                'type' => 'Comercial',
                'sort_order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SPA RETREAT',
                'slug' => 'spa-retreat',
                'description' => 'Retiro de spa com ambientes relaxantes.',
                'status' => 1,
                'location' => 'Bali, Indonésia',
                'type' => 'Resort',
                'sort_order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'EDUCATIONAL CAMPUS',
                'slug' => 'educational-campus',
                'description' => 'Campus educacional inovador.',
                'status' => 1,
                'location' => 'Boston, EUA',
                'type' => 'Institucional',
                'sort_order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'GREEN OFFICE PARK',
                'slug' => 'green-office-park',
                'description' => 'Parque de escritórios com foco em sustentabilidade.',
                'status' => 1,
                'location' => 'Curitiba, Brasil',
                'type' => 'Corporativo',
                'sort_order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'HISTORIC MUSEUM',
                'slug' => 'historic-museum',
                'description' => 'Museu histórico com arquitetura preservada.',
                'status' => 1,
                'location' => 'Londres, Reino Unido',
                'type' => 'Institucional',
                'sort_order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CITY LIBRARY',
                'slug' => 'city-library',
                'description' => 'Biblioteca municipal moderna.',
                'status' => 1,
                'location' => 'Toronto, Canadá',
                'type' => 'Institucional',
                'sort_order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SEASIDE RESTAURANT',
                'slug' => 'seaside-restaurant',
                'description' => 'Restaurante à beira-mar com vista panorâmica.',
                'status' => 1,
                'location' => 'Nice, França',
                'type' => 'Comercial',
                'sort_order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'URBAN PARK',
                'slug' => 'urban-park',
                'description' => 'Parque urbano com áreas de lazer.',
                'status' => 1,
                'location' => 'Berlim, Alemanha',
                'type' => 'Institucional',
                'sort_order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DESERT RESORT',
                'slug' => 'desert-resort',
                'description' => 'Resort de luxo no deserto.',
                'status' => 1,
                'location' => 'Doha, Catar',
                'type' => 'Resort',
                'sort_order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
