<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Portfolio;
use App\Models\PortfolioCategory;
use Illuminate\Support\Facades\DB;

class PortfoliosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('portfolios')->delete();
        DB::table('portfolio_categories')->delete();

        PortfolioCategory::insert([
            [
                'name' => 'Residências',
                'slug' => 'residências',
            ],
            [
                'name' => 'Hotéis',
                'slug' => 'hotéis',
            ],
            [
                'name' => 'Shoppings',
                'slug' => 'shoppings',
            ],
            [
                'name' => 'Lojas',
                'slug' => 'lojas',
            ],
            [
                'name' => 'Corporativo',
                'slug' => 'corporativo',
            ],
            [
                'name' => 'Outros',
                'slug' => 'outros',
            ],
        ]);

        Portfolio::insert([
            [
                'title' => 'Classic Hotel Project',
                'slug' => 'classic-hotel-project',
                'description' => 'Projeto de hotel clássico com arquitetura sofisticada.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Resort Beach',
                'slug' => 'resort-beach',
                'description' => 'Resort à beira-mar com design contemporâneo.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Urban Loft',
                'slug' => 'urban-loft',
                'description' => 'Loft urbano com conceito aberto e industrial.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Corporate Tower',
                'slug' => 'corporate-tower',
                'description' => 'Torre corporativa de alto padrão.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Modern Villa',
                'slug' => 'modern-villa',
                'description' => 'Vila moderna com integração à natureza.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Industrial Complex',
                'slug' => 'industrial-complex',
                'description' => 'Complexo industrial sustentável.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mountain Chalet',
                'slug' => 'mountain-chalet',
                'description' => 'Chalé de montanha com vista panorâmica.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Luxury Apartments',
                'slug' => 'luxury-apartments',
                'description' => 'Apartamentos de luxo no centro urbano.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Coastal House',
                'slug' => 'coastal-house',
                'description' => 'Casa costeira com arquitetura sustentável.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Art Gallery Space',
                'slug' => 'art-gallery-space',
                'description' => 'Espaço de galeria de arte contemporânea.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Country House',
                'slug' => 'country-house',
                'description' => 'Casa de campo com design rústico.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Urban Mall',
                'slug' => 'urban-mall',
                'description' => 'Shopping center moderno e funcional.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spa Retreat',
                'slug' => 'spa-retreat',
                'description' => 'Retiro de spa com ambientes relaxantes.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Educational Campus',
                'slug' => 'educational-campus',
                'description' => 'Educational Campus inovador.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Green Office Park',
                'slug' => 'green-office-park',
                'description' => 'Green Office Park with focus on sustainability.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Historic Museum',
                'slug' => 'historic-museum',
                'description' => 'Historic Museum with preserved architecture.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'City Library',
                'slug' => 'city-library',
                'description' => 'Modern City Library.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Seaside Restaurant',
                'slug' => 'seaside-restaurant',
                'description' => 'Seaside Restaurant with panoramic views.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Urban Park',
                'slug' => 'urban-park',
                'description' => 'Urban Park with leisure areas.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DESERT RESORT',
                'slug' => 'desert-resort',
                'description' => 'Luxury Resort in the Desert.',
                'status' => 1,
                'location' => null,
                'type' => null,
                'sort_order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
